version: '2'
services:
  mydb:
    image: postgres:10
    ports:
      - 5422:5432/tcp
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always             # run as a service
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

#  dbadmin:
#    image: adminer
#    restart: always
#    ports:
#      - 8040:8080/tcp

  osait:
    image: odoo:12.0
    depends_on:
      - mydb
    ports:
      - "8060:8069/tcp"
    tty: true
    #command: -- --dev=reload
    #command: odoo scaffold /mnt/extra-addons/test_module
    volumes:      
      - ./etc/sait/data:/var/lib/odoo
      - ./addons:/mnt/addons
      - ./etc/sait/config:/etc/odoo
    restart: always             # run as a service

  opiercho:
    image: odoo:12.0
    depends_on:
      - mydb
    ports:
      - "8070:8069/tcp"
    tty: true
    #command: -- --dev=reload
    #command: odoo scaffold /mnt/extra-addons/test_module
    volumes:      
      - ./etc/piercho/data:/var/lib/odoo
      - ./addons:/mnt/addons
      - ./etc/piercho/config:/etc/odoo
    restart: always             # run as a service

volumes:
  db-data:
    driver: local